name: Hotelaria
description: "Sistema de gestÃ£o hoteleira premium v1."
publish_to: 'none'

version: 1.0.0+1

environment:

  sdk: '>=3.11.0 <4.0.0'

dependencies:
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  

  get_it: ^8.0.3

dev_dependencies:

  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/images/logo.png"