name: hotelaria
description: "Sistema de gestão hoteleira premium v1."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Aumentamos para 3.27 para suportar as novas APIs de Color (withValues)
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Gerenciador de dependências (Service Locator)
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Atualizado para as lints mais recentes
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Se você for usar imagens locais futuramente, a seção abaixo deve existir:
  # assets:
  #   - assets/images/